include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
    - "android/**"
    - "ios/**"
    - "web/**"

linter:
  rules:
    - always_declare_return_types
    - avoid_empty_else
    - prefer_final_locals
    - unnecessary_brace_in_string_interps
    - use_key_in_widget_constructors
