#!/usr/bin/env python3
"""
Turns the PSA's PSGC API into SQL that loads public.psgc_areas.

    PSGC_TOKEN=... python3 supabase/scripts/psgc_to_sql.py > psgc.sql
    psql "$DATABASE_URL" -f psgc.sql        # or paste into the SQL editor

The token is read from the environment so it never lands in git. The output
upserts, so running it again after a new PSGC release updates every row.
Standard library only.

Options:
    --version Q2_2026     PSGC release to read (default Q2_2026)
    --batch 1000          rows per INSERT statement
"""
import argparse, json, os, sys, time, urllib.parse, urllib.request
from concurrent.futures import ThreadPoolExecutor

API = "https://classification.psa.gov.ph/psgc/{version}/all"


def fetch_page(version, token, page):
    query = urllib.parse.urlencode({"token": token, "page": page})
    url = f"{API.format(version=version)}?{query}"
    for attempt in range(4):
        try:
            with urllib.request.urlopen(url, timeout=90) as res:
                return json.load(res)
        except Exception:
            if attempt == 3:
                raise
            time.sleep(2 ** attempt)


def fetch_all(version, token):
    first = fetch_page(version, token, 1)
    per_page = len(first["results"]) or 1
    pages = -(-first["count"] // per_page)
    with ThreadPoolExecutor(8) as pool:
        rest = pool.map(lambda p: fetch_page(version, token, p)["results"], range(2, pages + 1))
        rows = first["results"] + [row for page in rest for row in page]
    if len(rows) != first["count"]:
        sys.exit(f"Expected {first['count']} areas, got {len(rows)}.")
    return rows


def code_of(reg, prv=0, mun=0, bgy=0):
    """The PSA's 10-digit code (the API drops the leading zero)."""
    return f"{reg:02d}{prv:03d}{mun:02d}{bgy:03d}"


def population_2024(row):
    for p in row.get("populations") or []:
        if p.get("year") == 2024:
            digits = "".join(ch for ch in str(p.get("population", "")) if ch.isdigit())
            return int(digits) if digits else None
    return None


def build(rows):
    by_code = {code_of(r["reg"], r["prv"], r["mun"], r["bgy"]): r for r in rows}

    def name(code):
        row = by_code.get(code)
        return " ".join(row["area_name"].split()) if row else ""

    def level(code):
        row = by_code.get(code)
        return row["geographic_level"] if row else None

    out = []
    for r in rows:
        reg, prv, mun, bgy = r["reg"], r["prv"], r["mun"], r["bgy"]
        code = code_of(reg, prv, mun, bgy)
        region = code_of(reg)
        top = code_of(reg, prv)                 # province, or a city with none
        local = code_of(reg, prv, mun)          # city, municipality or sub-municipality
        lvl = r["geographic_level"]

        # "Province" is the province, or the region where the city has none
        # (Metro Manila, highly urbanised cities).
        province = name(top) if level(top) == "Prov" else name(region)

        if lvl == "Reg":
            parent, city, province = None, "", ""
        elif prv and not mun and not bgy:       # Prov, HUC, special area
            parent, city = region, ""
        elif not bgy:                           # City, Mun, SubMun
            parent, city = top, ""
        else:                                   # Bgy
            home = local if mun and local in by_code else top
            parent = home
            if level(home) == "SubMun":
                city = f"{name(home)}, {name(top)}"
            else:
                city = name(home)

        out.append({
            "code": code,
            "name": " ".join(r["area_name"].split()),
            "level": lvl or "",
            "region_code": region,
            "parent_code": parent,
            "city": city,
            "province": province if lvl != "Reg" else "",
            "urban_rural": r.get("urban_rural") or "",
            "population_2024": population_2024(r),
            "version": r.get("version") or "",
        })
    return out


def literal(value):
    if value is None:
        return "null"
    if isinstance(value, int):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


COLUMNS = ["code", "name", "level", "region_code", "parent_code", "city",
           "province", "urban_rural", "population_2024", "version"]


def to_sql(areas, batch):
    yield "-- Generated by supabase/scripts/psgc_to_sql.py"
    yield "begin;"
    updates = ", ".join(f"{c} = excluded.{c}" for c in COLUMNS[1:])
    for i in range(0, len(areas), batch):
        values = ",\n".join(
            "(" + ", ".join(literal(a[c]) for c in COLUMNS) + ")" for a in areas[i:i + batch])
        yield (f"insert into public.psgc_areas ({', '.join(COLUMNS)}) values\n{values}\n"
               f"on conflict (code) do update set {updates};")
    yield "commit;"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", default="Q2_2026")
    parser.add_argument("--batch", type=int, default=1000)
    args = parser.parse_args()
    token = os.environ.get("PSGC_TOKEN", "").strip()
    if not token:
        sys.exit("Set PSGC_TOKEN to your PSA API token.")
    areas = build(fetch_all(args.version, token))
    for statement in to_sql(areas, args.batch):
        print(statement)
    print(f"-- {len(areas)} areas", file=sys.stderr)


if __name__ == "__main__":
    main()
