import 'enums.dart';

/// One entry in the Alerts feed.
///
/// Alerts are generated by the repositories whenever domain state changes (a
/// report is verified, a safe spot closes, a saved route picks up a hazard),
/// so the feed is always a faithful log rather than a separate mock list.
class AlertItem {
  const AlertItem({
    required this.id,
    required this.kind,
    required this.title,
    required this.body,
    required this.createdAt,
    this.isRead = false,
    this.reportId,
    this.safeSpotId,
    this.routeId,
    this.onSavedRoute = false,
  });

  final String id;
  final AlertKind kind;
  final String title;
  final String body;
  final DateTime createdAt;
  final bool isRead;

  /// Deep-link targets. Tapping an alert opens whichever of these is set.
  final String? reportId;
  final String? safeSpotId;
  final String? routeId;

  /// Drives the "My Saved Routes" vs "Everywhere Nearby" filter.
  final bool onSavedRoute;

  AlertItem copyWith({bool? isRead}) => AlertItem(
    id: id,
    kind: kind,
    title: title,
    body: body,
    createdAt: createdAt,
    isRead: isRead ?? this.isRead,
    reportId: reportId,
    safeSpotId: safeSpotId,
    routeId: routeId,
    onSavedRoute: onSavedRoute,
  );

  Map<String, dynamic> toJson() => <String, dynamic>{
    'id': id,
    'kind': kind.id,
    'title': title,
    'body': body,
    'createdAt': createdAt.toIso8601String(),
    'isRead': isRead,
    'reportId': reportId,
    'safeSpotId': safeSpotId,
    'routeId': routeId,
    'onSavedRoute': onSavedRoute,
  };

  factory AlertItem.fromJson(Map<String, dynamic> json) => AlertItem(
    id: json['id'] as String,
    kind: AlertKind.fromId(json['kind'] as String?),
    title: json['title'] as String? ?? '',
    body: json['body'] as String? ?? '',
    createdAt: DateTime.parse(json['createdAt'] as String),
    isRead: json['isRead'] as bool? ?? false,
    reportId: json['reportId'] as String?,
    safeSpotId: json['safeSpotId'] as String?,
    routeId: json['routeId'] as String?,
    onSavedRoute: json['onSavedRoute'] as bool? ?? false,
  );
}
